TARGET = XK-1
APP_NAME =
XCC_FLAGS = -O2
USED_MODULES = module_lib_fixed_8_24 module_lib_uint_32 module_lib_uint_64

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.


# Use the main Makefile from module_xcommon
-include ../module_xcommon/build/Makefile.common
-include ../../xcommon/module_xcommon/build/Makefile.common
